version: '3'
services:
  runner:
    build: .
    command: |
      side-runner-py
        --test-file /src/examples/*.side
        --output-dir /out
        --hook-scripts-dir /src/hooks
        --driver-retry-count 10
    volumes:
      - "~/out:/out"
  webdriver:
    image: selenium/standalone-chrome-debug
    ports:
    - '5900:5900'
  webpage:
    image: nginx:alpine
    volumes:
    - "$PWD/tests/e2e/html:/usr/share/nginx/html"
